### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mjw349** [songweizhi/HgtSIM#1]
Hello,

I am receiving this error when trying to run your program. I am trying to simulate an HGT event between the bacteria Wolbachia and its host Drosophila. My command line is this:

`$ python HgtSIM.py -t Wolbachia.fasta -i 0 -d distribution_of_transfers.txt -f recipient_genome -x fasta
`
My recipient_genome folder contains a Drosophila multi-fasta sequence called Drosophila_test_genome (only part of the genome, not the entire thing). My distribution_of_transfers.txt is a text file with the line "Drosophila_test_genome, Wolbachia". [I eventually want to use the entire Drosophila genome as a recipient genome along with the keep_cds flag, but thought to try out something simpler at first.]

Here is the error that I get:
```
Running random mutation...
Processing: Wolbachia
Mutants of input sequences exported to: /Users/mjw349/Desktop/HgtSIM-master/test/outputs_0_1-0-1-1/input_sequence_mutant_nc.fasta
Get nucleotide identity (by BlastN) between input sequences and their mutants
Get amino acids identity (by BlastP) between input sequences and their mutants
Random mutation report exported to: /Users/mjw349/Desktop/HgtSIM-master/test/outputs_0_1-0-1-1/Step_1_mutation_report.txt
dynamic_flanking_seqs: False
Running random insertion...
Traceback (most recent call last):
  File "../HgtSIM.py", line 667, in <module>
    new_seq, for_report = get_random_insertion(keep_cds, recipient_ctg_nc, insert_sequence_seq_list_new, insert_sequence_id_list_new, dynamic_flanking_seqs, lf_dict, rf_dict, common_stop_sequence_l, common_stop_sequence_r, recipient_genome_id, recipient_ctg_id, recipient_ctg_intergenic_list)
  File "../HgtSIM.py", line 136, in get_random_insertion
    first_sequence = [1, random_intergenics_sorted[n]]
IndexError: list index out of range
```
When I use the example given with the program, the example runs fine. So I believe my files are not set up properly.

Any insight would be appreciated.
Many thanks!
Sincerely,
Miwa

**Comment by songweizhi** [comment]
Could you send me your input files? I can then have a look what happened. my email is songwz03@gmail.com

**Comment by songweizhi** [comment]
Hi Miwa,
The error occurred because the third ctg in Drosophila_genome_multi.fasta has no transfer assigned to it. I have fixed the bug, should be fine this time.
Cheers,
Weizhi

**Comment by mjw349** [comment]
Hi Weizhi,

Thank you very much!! It works perfectly for me now.

Best,
Miwa
