### ISSUE TITLE
KeyError: 'TAG'

### ISSUE THREAD

**Issue by Zjianglin** [songweizhi/HgtSIM#2]
Hello developers,
I'm trying to simulate some HGT by transfering several STX elements into a Ecoli_K12 genome, but I have entountered a runtime error below:
```
2018-12-11 17:18:22 Mixed mode set to False
2018-12-11 17:18:22 Running random mutation
Traceback (most recent call last):
  File "HgtSIM.py", line 434, in <module>
    codon_to_aa_dict[current_codon_for_samesense_mutation],
KeyError: 'TAG'
```
I guess that there are some error in my `sequences_of_transfers.fasta`, but I don't know what exact error it is, could you please help me?

**Comment by songweizhi** [comment]
can you please send me your input files? my email is songwz03@gmail.com. Thanks.

**Comment by Zjianglin** [comment]
I have sent a message to your email, please check it.

**Comment by songweizhi** [comment]
Hi, Zjiang,
The file sequences_of_gene_transfers.fasta provides the sequences of a list of GENES (from ATG to TAA/TAG) to be transferred, but not the genome/contig sequence.
Cheers,

**Comment by Zjianglin** [comment]
Okay, thank you very much.
